listen: "localhost:8042"
routes:
    /:
      load_balancer_strategy: "single"
      cache:
        enabled: false
      backends:
        - url: "http://localhost:8080"
    /api:
      load_balancer_strategy: "single"
      cache:
        enabled: true
        max_size: 500
        max_entry_size: 1
        ttl: 60
      backends:
        - url: "http://localhost:8081"
