listen: "localhost:8042"
routes:
    /:
      lb:
        strategy: "single"
      cache:
        enabled: false
      backends:
        - url: "http://localhost:8080"
    /api:
      lb:
        strategy: "round_robin"
      cache:
        enabled: true
        max_size: 500
        max_entry_size: 1
        ttl: 60
      backends:
        - url: "http://localhost:8081"
        - url: "http://localhost:8082"
        - url: "http://localhost:8083"
